collections:
  research:
    output: true
    permalink: /:collection/:path/
    
defaults:
  # _research
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: false
      share: true
